default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: dbuser
  password:
  host: localhost

development:
  <<: *default
  database: simple_form_training_development

test:
  <<: *default
  database: simple_form_training_test

production:
  <<: *default
  database: simple_form_training_production
  username: simple_form_training
  password: <%= ENV['SIMPLE_FORM_TRAINING_DATABASE_PASSWORD'] %>
